name: Deploy to External Repo (damaelee8.github.io)

on:
  push:
    branches:
      - main  # 只要你推送源码到 main 分支，就会触发
  workflow_dispatch: # 保留手动触发按钮

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build site
        # 这里的 --webpack 是为了解决你之前遇到的 Turbopack 内存溢出错误
        run: npm run build -- --webpack 

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # 记得在仓库 A 的 Settings 里设置这个密钥（Secret）
          API_TOKEN_GITHUB: ${{ secrets.MY_DEPLOY_TOKEN }}
        with:
          source-directory: 'out'
          destination-github-username: 'damaelee8'
          destination-repository-name: 'damaelee8.github.io'
          user-email: damaelee8@gmail.com # 换成你的 GitHub 邮箱
          target-branch: main
